language: node_js

node_js: "4.1"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  
  - npm install -g gulp bower
  - bower install  
  - sleep 1

script:
  - gulp karma
  - gulp mocha-on-travis

notifications:  
  email: false

services: 
  - mongodb
  - redis-server
  
after_script:
  - gulp coverage
  