language: node_js

node_js: "4.1"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g bower
  - npm install -g gulp
  - npm start 
  - npm run update-webdriver
  - bower install -f

script:
  - gulp mocha
  - gulp karma
  - gulp protractor  

services: 
  - mongodb
  - redis-server