language: node_js

node_js: "4.1"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  
  - npm install -g gulp 
  - npm run update-webdriver 
  - sleep 1

script:
  - gulp karma
 

services: 
  - mongodb
  - redis-server