language: node_js

node_js: "4.1"

before_script:
  - npm install -g bower gulp-cli mocha
  - npm run-script test-on-travis
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gulp mocha
  - gulp karma
  - gulp protractor  

services: 
  - mongodb
  - redis-server